version: '3'
services:
  web:
    build: .
    container_name: fac
    volumes:
      - ./python3:/var/www
    ports:
      - 8000:8000
    command: bash -c "python manage.py runserver"
    tty: true
